routes/admin.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\QuestionsController;
use App\Http\Controllers\Admin\ResponceController;
use App\Http\Controllers\Admin\OptionsController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\SurvyController;
use App\Http\Controllers\Admin\AnswerController;
use App\Http\Controllers\Controller;
use App\Models\Responce;
use App\Notifications\SurvyTaked;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::name('admin.')->group(function () {


    Route::middleware(['auth', 'verified', 'IsAdmin'])->group(function () {

        Route::get('dashboard', [Controller::class, 'dash'])->name('dashboard');
        Route::resource('survies', SurvyController::class);
        Route::resource('answers', AnswerController::class);
        Route::resource('options', OptionsController::class);
        Route::resource('category', CategoryController::class);
        Route::resource('responce', ResponceController::class)->except([
            'create', 'store', 'update', 'edit', 'delete'
        ]);;
        Route::post('checkout/{id}', [ResponceController::class, 'checkout'])->name('responce.checkout');

        Route::get('/', function () {
            Response::find(3)->notify(new SurvyTaked);
            return view('admin.dashboard');
        });


    });


});

routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Front\SurvyController;
use App\Http\Controllers\Front\CategoryController;
use App\Http\Controllers\Admin\ResponceController;
use App\Models\Responce;
use App\Notifications\SurvyTaked;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [CategoryController::class, 'index']);

Route::get('/redirect', [Controller::class, 'redirect']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';


//===================================survy
Route::resource('survy', SurvyController::class);
Route::resource('category', CategoryController::class);

Route::resource('responce', ResponceController::class)->only('store');

app/Models/Responce.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Responce extends Model
{
    use HasFactory;
    protected $fillable = [
        'survy_id', 'category_id', 'statuse'
    ];
//    public function cat(){ //property
//        return $this->belongsTo(Category::class, 'category_id');
//    }
    public function answers(){
        return $this->hasMany(Answer::class);

    }
    public function survies (){
        return $this->belongsTo(Survy::class, 'survy_id');

    }
}

app/Http/Controllers/Admin/ResponceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use App\Models\Answer;
use App\Models\Category;
use App\Models\Responce;
use App\Models\Survy;
use Illuminate\Http\Request;
use App\Notifications\SurvyTaked;

class ResponceController extends Controller
{


    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categories = Category::get();

        //    dd($categories);
        return view('admin.pages.responce.category', compact(['categories']));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
//        dd($request);
        $input = $request->input();

        $survy_id = $request->id;
        $questions_count = Survy::find($survy_id)->questions()->count();

        $survy = Survy::find($survy_id);


        $responce = Responce::create([
            'survy_id' => $survy_id,
            'category_id' => $survy->category_id,
        ]);


        $survy = Survy::find($request->id);
        $questions = $survy->questions;
        for ($i = 1; $i <= $questions_count; $i++) {
            $c = $i;
            if (is_array($input[$i])) {
                $j = Answer::query()->create([
                    'responce_id' => $responce->id,
                    'answer' => json_encode($input[$i]),
                    'q_num' => $c,
                ]);
            }
            else
                {
                $j = Answer::query()->create([
                    'responce_id' => $responce->id,
                    'answer' => $input[$i],
                    'q_num' => $c,
                ]);
            }


        }
        return redirect('/')->with(['success' => 'your feedback has been recived thanks for your time']);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $category_id = $id;
        $survies = Survy::where('category_id', $id)->get();


        if ($survies)
            return view('admin.pages.responce.survies', compact(['survies']));
        return redirect(route('admin.responce.index'))->with(['mis' => 'there is no responce yet']);


    }



    //dd($answers);


    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Answer::where('responce_id',$id)->delete();
        Responce::where('id', $id)->delete();
        return redirect()->back()->with(['success' => 'the responce has been deleted successfully']);
    }

    public function checkout($id)
    {
        Responce::where('id', $id)->update([
            'statuse' => '1',
        ]);
        return redirect()->back();
    }
}


//store
//
//    dd($request);
//        $category_id= $request->category_id;
//       $respons = Response::create([
//          'name' => $request->name,
//       'email'=> $request->email,
//           'answer'=>$request->answer,
//           'category_id'=>$request->category_id

//       ]);
//        $questions = Question::find(20);
//        $category =$questions->categories;
//        dd($category);

//  Response::create([
//            'answer' => json_encode($data),
//            'category_id' => $category_id,
//        ]);


//      $responce=[$request];
//     dd($responce);
//        $category_id=$request->input('id');
//
//        $category =Category::find($category_id);
//        $questions= $category->questions;


//       $input['category'] = json_encode($data);
//        Response::create([
//            'answer' => json_encode($data),
//            'category_id' => $category_id,


// dd($questions);
//  $responce=
//       dd($responce);
//        Response::where('category_id', $category_id)->get();
//        $responces = $category->responces ;
//        //   dd($responces);
//        foreach ($responces as $responce){
//
//            $answers[$responce->id]=json_decode($responce->answer);

resources/views/admin/pages/responce/answers.blade.php
@extends('admin.layout.app')
@section('content')


    @if(Session::has('success'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('success')}}</h5>
        </div>
    @endif
    @if(Session::has('deletemessage'))
        <div class="alert alert-danger" role="alert">
            <h5> {{Session::get('deletemessage')}}</h5>
        </div>
    @endif
    @if(Session::has('successp'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('successp')}}</h5>
        </div>
    @endif

    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg hallon-main ">








        <div class="container-fluid py-4">


            <div class="helen">

            </div>


            <table class="table"  id="myusertable">
                <thead>
                <tr>
                    <th scope="col">
                        operations
                    </th>

                    @foreach($questions as $question)

                        {{--                        @foreach($responce->answer as $name)--}}



                        <th scope="col">
                            {{$question->text}}
       م                 </th>


                        {{--                    @endforeach--}}
                    @endforeach


                </tr>
                </thead>
                <tbody>

                @foreach($responces as $responce )

                    <tr>
                        <td scope="col" class="border">

                            <form action="{{ route('admin.responce.destroy', $responce->id)}}" method="POST" class="d-inline-block">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-primary ">Delete responce </button>

                            </form>



                                    @if($responce->statuse==0)

                                        <form  action="{{route('admin.responce.checkout', $responce->id)}}" method="POST"  id="myForm" enctype="multipart/form-data">

                                            @csrf
                                            @method('POST')
                                            <button type="submit" class="btn btn-primary ">click if you <br> checked out</button>
                                        </form>

                                    @endif


                        </td>
                        @foreach($responce->answers as  $an)



                            <td scope="col" class="border ">

                                <p> {{$an->answer}} </p>



                                {{--                           {{$answer[$question->name]}}--}}
                            </td>


                        @endforeach

                        {{--            <td scope="col" class="border"> <a href="{{route('admin.responce.destroy', array_search('answer', $answers)  )}}" class="btn btn-danger">delete</a></td>--}}

                    </tr>


@endforeach
                </tbody>


            </table>








@endsection

resources/views/admin/pages/responce/category.blade.php
@extends('admin.layout.app')
@section('content')






    @if(Session::has('success'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('success')}}</h5>
        </div>
    @endif
    @if(Session::has('mis'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('mis')}}</h5>
        </div>
    @endif







    <div class="container">

        <div class="row x">

            <div class=" col-12">
                <br>


                <table class="table" id="myusertable">
                    <thead>
                    <tr class="border-2">
                        <th scope="col">category name</th>
                        <th scope="col">operation</th>
                    </tr>
                    </thead>
                    <tbody>

                    @if(isset($categories) && $categories -> count() > 0)
                        @foreach($categories as $category)

                            <tr class="border">


                                <th scope="col" class="border-2"><h4>{{ $category->name }}</h4></th>
                                <th scope="col" class="border-2">
                                    <a href="{{route('admin.responce.show', $category->id)}}" class="btn btn-info"><h3>
                                            show responces for {{$category->name}}</h3></a>

                                </th>
                @endforeach
                @endif


            </div>
            <br>


        </div>
    </div>
    </div>






@endsection

resources/views/admin/pages/responce/survies.blade.php
@extends('admin.layout.app')
@section('content')


    @if(Session::has('success'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('success')}}</h5>
        </div>
    @endif
    @if(Session::has('deletemessage'))
        <div class="alert alert-danger" role="alert">
            <h5> {{Session::get('deletemessage')}}</h5>
        </div>
    @endif
    @if(Session::has('successp'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('successp')}}</h5>
        </div>
    @endif
    @if(Session::has('mis'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('mis')}}</h5>
        </div>
    @endif
    @if(Session::has('delete'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('delete')}}</h5>
        </div>
    @endif

    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg hallon-main ">


        <div class="container-fluid py-4 mr-5 ml-5">


            @if(isset($survies) && $survies -> count() > 0)
                @foreach($survies as $survy)
                    <div class="border pt-3 p-lg-2 layout_padding mx-10 my-3 ">
                        <h6 class="d-inline-block">show responces: </h6>   <a
                            href="{{route('admin.answers.show', $survy->id)}}" class="btn btn-success d-inline-block bg-cover">
                            <h5 class="d-inline-block">{{$survy->survy}}</h5></a>
                        @if($survy->reseponces-> count()==0)
                        <form action="{{route('admin.survies.destroy', $survy->id)}}" method="POST" class="ml-5 d-inline-block">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="ml-5 btn btn-primary d-inline-block">Delete Survies</button>
                            </form>
                        @endif
                        <p class="text-center bg-gradient-faded-">
                        <h5 class="text-center color-foreground"> {{$survy->description}}</h5>
                        </p>
                    </div>
                @endforeach
            @endif


        </div>










@endsection