routes/admin.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\QuestionsController;
use App\Http\Controllers\Admin\ResponceController;
use App\Http\Controllers\Admin\OptionsController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\SurvyController;
use App\Http\Controllers\Admin\AnswerController;
use App\Http\Controllers\Controller;
use App\Models\Responce;
use App\Notifications\SurvyTaked;
use App\Models\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::name('admin.')->group(function () {


    Route::middleware(['auth', 'verified', 'IsAdmin'])->group(function () {

        Route::get('dashboard', [Controller::class, 'dash'])->name('dashboard');
        Route::resource('survies', SurvyController::class);
        Route::resource('answers', AnswerController::class);
        Route::resource('options', OptionsController::class);
        Route::resource('category', CategoryController::class);
        Route::resource('responce', ResponceController::class)->except([
            'create', 'store', 'update', 'edit', 'delete'
        ]);;
        Route::post('checkout/{id}', [ResponceController::class, 'checkout'])->name('responce.checkout');

        Route::get('/', function () {
            Response::find(3)->notify(new SurvyTaked);
            return view('admin.dashboard');
        });


    });


});

routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Front\SurvyController;
use App\Http\Controllers\Front\CategoryController;
use App\Http\Controllers\Admin\ResponceController;
use App\Models\Responce;
use App\Notifications\SurvyTaked;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [CategoryController::class, 'index']);

Route::get('/redirect', [Controller::class, 'redirect']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';


//===================================survy
Route::resource('survy', SurvyController::class);
Route::resource('category', CategoryController::class);

Route::resource('responce', ResponceController::class)->only('store');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use App\Models\Response;

class Category extends Model
{

    use HasFactory;
    protected $fillable = [
        'name'
    ];



//
//    public function questions (): BelongsToMany
//    {
//        return $this->belongsToMany(Question::class, 'question_category', 'category_id', 'question_id', 'id', 'id');
//    }

    public function survies()
    {
        return $this->hasMany(Survy::class);
    }


public function responces (){
    return $this->hasMany(Responce::class);

}


}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {

        $categories = Category::get();
        //    dd($categories);
        return view('admin.pages.Categories.category', compact(['categories']));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        Return view('admin.pages.categories.createcategory');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {


        $validator = Validator::make($request->all(), [


            'name' => ['required', 'string', 'max:255'],

        ]);

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        $input = $request->all();


        Category::create($input);
        return redirect('/admin/category')->with(['success' => 'تم إضافة الفئة بنجاح']);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $category = Category::find($id);
        return view('admin.pages.categories.editcategory', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {


        $validator = Validator::make($request->all(), [


            'name' => ['required', 'string', 'max:255'],

        ]);

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        Category::where('id', $id)
            ->update(['name' => $request->input('name')]);

        return redirect('/admin/category')->with(['success' => 'تم تعديل الفئة بنجاح']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {


        Category::find($id)->delete();
        return redirect('/admin/category')->with(['success' => 'تم حذف الفئة بنجاح']);
    }
}

app/Http/Controllers/Front/CategoryController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Survy;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $catnav = Category::get();
//        dd($catnav);
        return view('front.home', compact('catnav'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {


        $catnav = Category::get();
        $survies = Survy::where('category_id', $id)->get();

        return view('front.pages.survy.survies', compact(['survies', 'catnav']));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/admin/pages/categories/category.blade.php
@extends('admin.layout.app')
@section('content')




    @if(Session::has('success'))
        <div class="alert alert-success" role="alert">
            <h5>{{Session::get('success')}}</h5>
        </div>
    @endif







    <div class="container">

        <div class="row x align-content-md-center">

            <div class=" col-12">
                <br>
                <br>
                <br>


                <div class="helen">
                    <a href="{{ Route('admin.category.create') }}" class="btn btn-success p-2  ">create</a>
                </div>

                <table class="table" id="mytable" class="align-content-center btn-outline-dark-blue">
                    <thead>
                    <tr>


                        {{--                        @foreach($responce->answer as $name)--}}

                        <th scope="col">
                            <h2 class=""> Category name</h2>

                        </th>
                        <th scope="col">
                            <h2> operation</h2>

                        </th>


                        {{--                    @endforeach--}}

                    </tr>
                    </thead>

                    <tbody>


                    @foreach($categories as $category)
                        <tr>
                            <td scope="col" class="border">

                                <h3>
                                    {{$category->name}}
                                </h3>
                            </td>

                            <td scope="col" class="border">

                                <div class="helen">

                                    {{--                                    <a href="{{ route('admin.showproduct',$category->id) }}" class="btn btn-primary p-2">show related product</a>--}}
                                    <a href="{{ route('admin.category.edit', $category->id) }}"
                                       class="btn btn-success d-lg-inline-block">edit category name</a>
                                    <form action="{{ route('admin.category.destroy', $category->id) }}" method="POST"
                                          class="d-inline-block">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-primary ">Delete Category</button>

                                    </form>
                                </div>
                            </td>


                        </tr>
                    @endforeach


                    </tbody>


                </table>


            </div>
        </div>
    </div>






@endsection

resources/views/admin/pages/categories/createcategory.blade.php
@extends('admin.layout.app')
@section('content')







    <div class="container">

        <div class="row x">

            <div class=" col-12">
                <br>
                <br>
                <br>
                <form action="{{ route('admin.category.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">


                        <div class="form-group">
                            <label for="formGroupExampleInput">name of category</label>
                            <input type="text" name="name" id="name-of-product" placeholder="name of category">
                            @error('name')
                            <small class="'form-text text-danger">{{$message}}</small>
                            @enderror
                        </div>

                        <br>
                        <div>
                            <button type="submit" class="btn btn-primary p-2 m-2">Submit</button>
                        </div>

                    </div>

                </form>
            </div>

            <div class="col-sm">

            </div>
        </div>

    </div>



@endsection

resources/views/admin/pages/categories/editcategory.blade.php
@extends('admin.layout.app')
@section('content')







    <div class="container">

        <div class="row x">

            <div class=" col-12">
                <br>
                <br>
                <br>
                <form action="{{ route('admin.category.update', $category->id) }}" method="POST">
                    @csrf
                    @method('PATCH')


                    <div class="form-group">
                        <label for="formGroupExampleInput">name of category</label>
                        <input type="text" name="name" id="name-of-category" placeholder="name of category"
                               value="{{$category->name}}">
                        @error('name')
                        <small class="'form-text text-danger">{{$message}}</small>
                        @enderror
                    </div>

                    <br>
                    <div>
                        <button type="submit" class="btn btn-primary p-2 m-2">Submit</button>
                    </div>

            </div>

            </form>
        </div>

        <div class="col-sm">

        </div>
    </div>

    </div>



@endsection